### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by drownload** [APSL/django-yubin#35] opened 2018-02-02 20:35 UTC
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/healersource/lib/python2.7/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/healersource/lib/python2.7/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/healersource/lib/python2.7/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/healersource/lib/python2.7/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/healersource/webapps/hs/env/lib/python2.7/site-packages/django_yubin/management/commands/send_mail.py", line 56, in handle
    message_limit=options['message_limit'])
  File "/home/healersource/webapps/hs/env/lib/python2.7/site-packages/django_yubin/engine.py", line 113, in send_all
    blacklist=blacklist)
  File "/home/healersource/webapps/hs/env/lib/python2.7/site-packages/django_yubin/engine.py", line 207, in send_queued_message
    smart_str(message.encoded_message).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 559: ordinal not in range(128)

**Comment by sastred** [comment] 2018-02-06 11:06
Hi @drownload,

Please, could you add the content of the email (or at least the relevant part of it) that causes the error?

**Comment by drownload** [comment] 2018-02-17 07:55
Looks like this is happening anywhere there is Content-Transfer-Encoding: 8bit (instead of 7bit)

Here is an example:

MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Subject: New Specialty: Integrative Massage
From: HealerSource (no reply) <no_reply@healersource.com>
To: admin@healersource.com
Date: Tue, 06 Feb 2018 18:29:55 -0000
Message-ID: <20180206182955.10513.50810@wf-207-38-92-79.webfaction.com>
Reply-To: HealerSource (no reply) <no_reply@healersource.com>

Description:
<p>
<span style="">
Integrative
massage uses multiple massage techniques to obtain the client’s needs &amp;
wants.
</span>
Massage modalities that may be used, but not limited to: Swedish
massage, Deep Tissue massage, Trigger Point Therapy massage, Thai massage, Shiatsu
massage, Structural massage, Sports massage and Acupressure. . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . .
<o:p>
</o:p>
</p>

Healer: lilwoow_at_hotmail_com, lilwoow_at_hotmail_com

lilwoow@hotmail.com

**Comment by sastred** [comment] 2018-02-22 17:42
Hi @drownload,

Could you try if version 1.0.4 fixes this issue?

**Comment by sastred** [comment] 2018-05-31 08:55
No feedback in a while, closing issue.

Fell free to open another issue if the problem is not resolved.

**Closed by sastred** 2018-05-31 08:55 UTC
